theme: jekyll-theme-minimal
title: Iago Lourenço Corrêa
description: This website presents my research background, for now it may be really short, but I'm working on it! Feel free to contact me.

logo: /assets/img/profile.jpg