theme: jekyll-theme-minimal
title: test_title_1
description: test_description

social-network-links:
  email: "someone@example.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: c/daattali
  
  avatar: "https://scontent.fpet2-1.fna.fbcdn.net/v/t1.6435-9/133913504_3392383587555155_2879823486196283560_n.jpg?_nc_cat=101&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=hmEQjq_iFsoAX8WWuTm&_nc_ht=scontent.fpet2-1.fna&oh=513d65b5ca57a20bfe8e5701857c8451&oe=60FB1004"
