theme: jekyll-theme-minimal
title: Welcome!
description: This website presents my research background, for now it may be really short, but I'm working on it! Feel free to contact me.

#title_pt: Boas-vindas!
#description_pt: Este site

#title_jp: いらっしゃい
#description_jp:　このサイト

logo: /assets/img/profile.jpg